/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/racer.glb
Author: CAPTAAINR (https://sketchfab.com/CAPTAAINR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-racertexturedrigged-b5eb8b47788049dcb1714276f3601497
Title: Black-Racer(Textured)(Rigged)
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Racer = (props) => {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/racer.glb");
	const { actions, names } = useAnimations(animations, group);

	useEffect(() => {
		actions[names[2]].reset().fadeIn(0.5).play();
	}, []);

	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Sketchfab_Scene">
				<group
					name="Sketchfab_model"
					rotation={[-Math.PI / 2, 0, 0]}
					scale={172.78}
				>
					<group
						name="0f343439b63744dfa0c3bad658e0d991fbx"
						rotation={[Math.PI / 2, 0, 0]}
						scale={0.01}
					>
						<group name="Object_2">
							<group name="RootNode">
								<group name="Flash_Blackracer">
									<group name="Object_5">
										<primitive object={nodes._rootJoint} />
										<group name="Object_7" rotation={[-Math.PI / 2, 0, 0]} />
										<group
											name="Flash_blackracer"
											rotation={[-Math.PI / 2, 0, 0]}
										/>
										<group name="Movement" />
										<skinnedMesh
											name="Object_8"
											geometry={nodes.Object_8.geometry}
											material={materials.Flash_blackracer_D}
											skeleton={nodes.Object_8.skeleton}
										/>
									</group>
								</group>
							</group>
						</group>
					</group>
				</group>
			</group>
		</group>
	);
};

useGLTF.preload("/racer.glb");
export default Racer;
