/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/test.glb
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Test(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/test.glb");
	const { actions, names } = useAnimations(animations, group);
	console.log(names);

	// useEffect(() => {
	// 	actions[names[0]].reset().fadeIn(0.5).play();
	// }, []);

	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<primitive object={nodes.mixamorigHips} />
					<skinnedMesh
						name="Ch39"
						geometry={nodes.Ch39.geometry}
						material={materials.Ch39_Body}
						skeleton={nodes.Ch39.skeleton}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/test.glb");
