/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/land.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Land(props) {
	const { nodes, materials } = useGLTF("/land.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				scale={0.1}
				geometry={nodes.Rocky_grassland_OBJ.geometry}
				material={materials["Material.001"]}
			/>
		</group>
	);
}

useGLTF.preload("/land.glb");
