/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState, useRef } from "react";
import { useGLTF, useAnimations, useCursor, Html } from "@react-three/drei";

import { useModalContext } from "../components/ModalContext";
import { useHoverContext } from "../components/HoverContext";
import { div } from "three/examples/jsm/nodes/Nodes.js";

export default function GenericPOI(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/genericPOIPruned.glb");
	const { actions } = useAnimations(animations, group);

	const { hoverText, setHoverText } = useHoverContext();

	const [discoveryText, setDiscoveryText] = useState(null);
	const [hovered, setHovered] = useState();
	useCursor(hovered);

	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				{/* Well */}
				<Html position={[-10, 35, -20]}>
					{discoveryText === "well" ? (
						<p
							className="w-[300px] p-4 text-[black] rounded-lg"
							style={{
								userSelect: "none",
								backgroundColor: "rgba(255, 255, 255, 0.6)",
							}}
						>
							"May your choices reflect your hopes, not your fears." — Nelson
							Mandela
						</p>
					) : null}
				</Html>
				<group
					name="well"
					position={[-1.09, 4, -0.625]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={3}
					className="w-[300px] cursor-pointer rounded-lg"
					style={{ userSelect: "none" }}
					onPointerOver={() => {
						setHovered(true);
						setDiscoveryText("well");
						event.stopPropagation(); // Prevent event propagation
					}}
					onPointerOut={() => {
						setHovered(false);
						setDiscoveryText(null);
					}}
				>
					<group name="pozoobjcleanermaterialmergergles">
						<mesh
							name="Object_10001"
							castShadow
							receiveShadow
							geometry={nodes.Object_10001.geometry}
							material={materials.lambert9SG}
						/>
						<mesh
							name="Object_2"
							castShadow
							receiveShadow
							geometry={nodes.Object_2.geometry}
							material={materials.blinn1SG}
						/>
						<mesh
							name="Object_4001"
							castShadow
							receiveShadow
							geometry={nodes.Object_4001.geometry}
							material={materials.lambert10SG}
						/>
						<mesh
							name="Object_5001"
							castShadow
							receiveShadow
							geometry={nodes.Object_5001.geometry}
							material={materials.lambert11SG}
						/>
						<mesh
							name="Object_6001"
							castShadow
							receiveShadow
							geometry={nodes.Object_6001.geometry}
							material={materials.lambert12SG}
						/>
						<mesh
							name="Object_7001"
							castShadow
							receiveShadow
							geometry={nodes.Object_7001.geometry}
							material={materials.lambert2SG}
						/>
						<mesh
							name="Object_8001"
							castShadow
							receiveShadow
							geometry={nodes.Object_8001.geometry}
							material={materials.lambert7SG}
						/>
						<mesh
							name="Object_9001"
							castShadow
							receiveShadow
							geometry={nodes.Object_9001.geometry}
							material={materials.lambert8SG}
						/>
					</group>
				</group>

				{/* Square Rune Stone */}
				<group
					name="main_rune_stone"
					position={[-190.221, -5, 226.823]}
					rotation={[-Math.PI / 2, 0, 1.064]}
					scale={100}
					className="w-[300px] cursor-pointer rounded-lg"
					style={{ userSelect: "none" }}
					onPointerOver={() => {
						setHovered(true);
						setDiscoveryText("runic-statue");
						event.stopPropagation(); // Prevent event propagation
					}}
					onPointerOut={() => {
						setHovered(false);
						setDiscoveryText(null);
					}}
				>
					<group
						name="93e44398c06f473ba0df0778aaea58c3fbx"
						rotation={[Math.PI / 2, 0, 0]}
					>
						<group name="RootNode003">
							<group name="One_LP" scale={0.01}>
								<mesh
									name="One_LP_One_Mat_0"
									castShadow
									receiveShadow
									geometry={nodes.One_LP_One_Mat_0.geometry}
									material={materials.One_Mat}
									position={[0, 2.447, -1.624]}
									scale={3.1}
								/>
							</group>
						</group>
					</group>
				</group>

				{/* Runic Statue */}
				<Html position={[-170, 40, 240]}>
					{discoveryText === "runic-statue" ? (
						<p
							className="w-[300px] p-4 text-[black] rounded-lg"
							style={{
								userSelect: "none",
								backgroundColor: "rgba(255, 255, 255, 0.6)",
							}}
						>
							I enjoy art of all kinds but I find that 3D art - especially art
							made for games - is the most beautiful.
						</p>
					) : null}
				</Html>
				<group
					name="runic_statue"
					position={[-198.393, -5, 240.613]}
					rotation={[Math.PI, -1.064, 0]}
					scale={12}
					className="w-[300px] cursor-pointer rounded-lg"
					style={{ userSelect: "none" }}
					onPointerOver={() => {
						setHovered(true);
						setDiscoveryText("runic-statue");
						event.stopPropagation(); // Prevent event propagation
					}}
					onPointerOut={() => {
						setHovered(false);
						setDiscoveryText(null);
					}}
				>
					<group
						name="Collada_visual_scene_group"
						rotation={[Math.PI / 2, 0, 0]}
					>
						<group name="base2">
							<mesh
								name="defaultMaterial"
								castShadow
								receiveShadow
								geometry={nodes.defaultMaterial.geometry}
								material={materials.EYES}
								position={[0, 0, 0.751]}
								rotation={[1.202, 1.521, 0.382]}
							/>
						</group>
					</group>
				</group>

				{/* Chest & Potions */}
				<Html position={[-170, 10, -210]}>
					{discoveryText === "chest-and-potions" ? (
						<p
							className="w-[300px] p-4 text-[black] rounded-lg"
							style={{
								userSelect: "none",
								backgroundColor: "rgba(255, 255, 255, 0.6)",
							}}
						>
							I spent over a decade in the healthcare field as a dietitian. Most
							of this time was working within the intensive care unit (ICU).
						</p>
					) : null}
				</Html>
				<group
					name="chest_and_postions"
					position={[-215, -5, -199]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.3}
					onPointerOver={() => {
						setHovered(true);
						setDiscoveryText("table-and-books");
						event.stopPropagation(); // Prevent event propagation
					}}
					onPointerOut={() => {
						setHovered(false);
						setDiscoveryText(null);
					}}
				>
					<group
						name="e40080bfb5634bc89c8b84bb094b36f6fbx"
						rotation={[Math.PI / 2, 0, 0]}
					>
						<group name="RootNode006">
							<group name="herbalistBox_final">
								<mesh
									name="herbalistBox_final_BoxMaterial_0"
									castShadow
									receiveShadow
									geometry={nodes.herbalistBox_final_BoxMaterial_0.geometry}
									material={materials["BoxMaterial.001"]}
								/>
							</group>
							<group
								name="Vial"
								position={[8.868, 1.941, -4.691]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial_VialYellow_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial_VialYellow_0.geometry}
									material={materials["VialYellow.001"]}
								/>
							</group>
							<group
								name="Vial001"
								position={[4.968, 1.941, -4.827]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial001_VialYellow_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial001_VialYellow_0.geometry}
									material={materials["VialYellow.001"]}
								/>
							</group>
							<group
								name="Vial002"
								position={[-1.177, 1.941, 1.423]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial002_VialYellow_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial002_VialYellow_0.geometry}
									material={materials["VialYellow.001"]}
								/>
							</group>
							<group
								name="Vial003"
								position={[9.328, 1.941, 1.326]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial003_VialYellow_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial003_VialYellow_0.geometry}
									material={materials["VialYellow.001"]}
								/>
							</group>
							<group
								name="Vial004"
								position={[9.245, 1.941, -1.973]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial004_VialRed_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial004_VialRed_0.geometry}
									material={materials["VialRed.001"]}
								/>
							</group>
							<group
								name="Vial005"
								position={[-6.349, 1.941, -4.716]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial005_VialYellow_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial005_VialYellow_0.geometry}
									material={materials["VialYellow.001"]}
								/>
							</group>
							<group
								name="Vial006"
								position={[8.888, 1.941, 4.618]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial006_VialRed_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial006_VialRed_0.geometry}
									material={materials["VialRed.001"]}
								/>
							</group>
							<group
								name="Vial007"
								position={[-7.581, 1.941, -1.852]}
								rotation={[-Math.PI / 2, 0, 1.008]}
								scale={100}
							>
								<mesh
									name="Vial007_VialRed_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial007_VialRed_0.geometry}
									material={materials["VialRed.001"]}
								/>
							</group>
							<group
								name="Vial008"
								position={[-4.538, 1.941, 1.641]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial008_VialRed_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial008_VialRed_0.geometry}
									material={materials["VialRed.001"]}
								/>
							</group>
							<group
								name="Vial009"
								position={[5.904, 1.941, 4.904]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial009_VialNeutral_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial009_VialNeutral_0.geometry}
									material={materials["VialNeutral.001"]}
								/>
							</group>
							<group
								name="Vial010"
								position={[3.214, 1.941, -1.669]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial010_VialRed_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial010_VialRed_0.geometry}
									material={materials["VialRed.001"]}
								/>
							</group>
							<group
								name="Vial011"
								position={[2.718, 1.941, 4.756]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial011_VialRed_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial011_VialRed_0.geometry}
									material={materials["VialRed.001"]}
								/>
							</group>
							<group
								name="Vial012"
								position={[-0.334, 1.941, -1.402]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial012_VialRed_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial012_VialRed_0.geometry}
									material={materials["VialRed.001"]}
								/>
							</group>
							<group
								name="Vial013"
								position={[-1.012, 1.941, 4.646]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial013_VialNeutral_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial013_VialNeutral_0.geometry}
									material={materials["VialNeutral.001"]}
								/>
							</group>
							<group
								name="Vial014"
								position={[-4.162, 1.941, -1.407]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial014_VialNeutral_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial014_VialNeutral_0.geometry}
									material={materials["VialNeutral.001"]}
								/>
							</group>
							<group
								name="Vial015"
								position={[-4.564, 1.941, 4.666]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial015_VialRed_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial015_VialRed_0.geometry}
									material={materials["VialRed.001"]}
								/>
							</group>
							<group
								name="Vial016"
								position={[0.719, 1.941, -4.608]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial016_VialRed_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial016_VialRed_0.geometry}
									material={materials["VialRed.001"]}
								/>
							</group>
							<group
								name="Vial017"
								position={[-2.957, 1.941, -3.753]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial017_VialRed_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial017_VialRed_0.geometry}
									material={materials["VialRed.001"]}
								/>
							</group>
							<group
								name="Vial018"
								position={[-9.245, 11.999, -10.693]}
								rotation={[-Math.PI / 2, 0, -0.412]}
								scale={100}
							>
								<mesh
									name="Vial018_VialNeutral_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial018_VialNeutral_0.geometry}
									material={materials["VialNeutral.001"]}
								/>
							</group>
							<group
								name="Vial019"
								position={[-5.858, 11.997, -10.408]}
								rotation={[-Math.PI / 2, 0, 0.477]}
								scale={100}
							>
								<mesh
									name="Vial019_VialYellow_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial019_VialYellow_0.geometry}
									material={materials["VialYellow.001"]}
								/>
							</group>
							<group
								name="Vial020"
								position={[-2.436, 12.001, -10.864]}
								rotation={[-Math.PI / 2, 0, 0.429]}
								scale={100}
							>
								<mesh
									name="Vial020_VialRed_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial020_VialRed_0.geometry}
									material={materials["VialRed.001"]}
								/>
							</group>
							<group
								name="Vial021"
								position={[1.107, 11.997, -10.418]}
								rotation={[-Math.PI / 2, 0, 0.497]}
								scale={100}
							>
								<mesh
									name="Vial021_VialRed_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial021_VialRed_0.geometry}
									material={materials["VialRed.001"]}
								/>
							</group>
							<group
								name="Vial022"
								position={[4.692, 12.003, -11.051]}
								rotation={[-Math.PI / 2, 0, -0.239]}
								scale={100}
							>
								<mesh
									name="Vial022_VialNeutral_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial022_VialNeutral_0.geometry}
									material={materials["VialNeutral.001"]}
								/>
							</group>
							<group
								name="Vial023"
								position={[8.53, 12, -10.774]}
								rotation={[-Math.PI / 2, 0, 0.445]}
								scale={100}
							>
								<mesh
									name="Vial023_VialRed_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial023_VialRed_0.geometry}
									material={materials["VialRed.001"]}
								/>
							</group>
							<group
								name="Vial024"
								position={[17.068, 0, 14.321]}
								rotation={[-Math.PI / 2, 0, -2.159]}
								scale={100}
							>
								<mesh
									name="Vial024_VialYellow_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial024_VialYellow_0.geometry}
									material={materials["VialYellow.001"]}
								/>
							</group>
							<group
								name="Vial025"
								position={[19.315, 0, 19.427]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vial025_VialNeutral_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial025_VialNeutral_0.geometry}
									material={materials["VialNeutral.001"]}
								/>
							</group>
							<group
								name="Vial026"
								position={[9.63, 1.577, 9.689]}
								rotation={[0, 0.448, 0]}
								scale={100}
							>
								<mesh
									name="Vial026_VialYellow_0"
									castShadow
									receiveShadow
									geometry={nodes.Vial026_VialYellow_0.geometry}
									material={materials["VialYellow.001"]}
								/>
							</group>
						</group>
					</group>
				</group>

				{/* Table & Books */}
				<Html position={[-210, 35, -200]}>
					{discoveryText === "table-and-books" ? (
						<p
							className="w-[300px] p-4 text-[black] rounded-lg"
							style={{
								userSelect: "none",
								backgroundColor: "rgba(255, 255, 255, 0.6)",
							}}
						>
							I spent over a decade in the healthcare field as a dietitian. Most
							of this time was working within the intensive care unit (ICU).
						</p>
					) : null}
				</Html>
				<group
					name="table_and_books"
					position={[-218.243, -4, -202.222]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={12}
					className="w-[300px] cursor-pointer rounded-lg"
					style={{ userSelect: "none" }}
					onPointerOver={() => {
						setHovered(true);
						setDiscoveryText("table-and-books");
						event.stopPropagation(); // Prevent event propagation
					}}
					onPointerOut={() => {
						setHovered(false);
						setDiscoveryText(null);
					}}
				>
					<group
						name="aff57fa65e0a4fcea9173300380bb6f3fbx"
						rotation={[Math.PI / 2, 0, 0]}
						scale={0.01}
					>
						<group name="RootNode007">
							<group name="Books">
								<mesh
									name="Books_lambert2_0"
									castShadow
									receiveShadow
									geometry={nodes.Books_lambert2_0.geometry}
									material={materials.lambert2}
								/>
							</group>
							<group name="Full_table">
								<mesh
									name="Full_table_lambert2_0"
									castShadow
									receiveShadow
									geometry={nodes.Full_table_lambert2_0.geometry}
									material={materials.lambert2}
								/>
							</group>
						</group>
					</group>
				</group>

				{/* Soldier's Closet */}
				<Html position={[90, 55, -320]}>
					{discoveryText === "soldiers-chest" ? (
						<p
							className="w-[300px] p-4 text-[black] rounded-lg"
							style={{
								userSelect: "none",
								backgroundColor: "rgba(255, 255, 255, 0.6)",
							}}
						>
							I love combat sports in general but I fascinated by the
							effectiveness of grappling. I've been doing Brazilian Jiu Jitsu
							(BJJ) for over 10 years and have my black belt in it.
						</p>
					) : null}
				</Html>
				<group
					name="soldier_closet"
					position={[133.15, -3, -323.088]}
					rotation={[-Math.PI / 2, 0, -2.109]}
					scale={4}
					className="w-[300px] cursor-pointer rounded-lg"
					style={{ userSelect: "none" }}
					onPointerOver={() => {
						setHovered(true);
						setDiscoveryText("soldiers-chest");
						event.stopPropagation(); // Prevent event propagation
					}}
					onPointerOut={() => {
						setHovered(false);
						setDiscoveryText(null);
					}}
				>
					<group
						name="1fb39e29f5ee44d689f53b73ae2c3451fbx"
						rotation={[Math.PI / 2, 0, 0]}
					>
						<group name="RootNode008">
							<group name="low">
								<group name="Bookcase_low">
									<mesh
										name="Bookcase_low_Bookcase1_0"
										castShadow
										receiveShadow
										geometry={nodes.Bookcase_low_Bookcase1_0.geometry}
										material={materials.Bookcase1}
									/>
									<mesh
										name="Bookcase_low_Bookcase_0"
										castShadow
										receiveShadow
										geometry={nodes.Bookcase_low_Bookcase_0.geometry}
										material={materials.Bookcase}
									/>
								</group>
								<group name="Flag_low">
									<mesh
										name="Flag_low_Bookcase_0"
										castShadow
										receiveShadow
										geometry={nodes.Flag_low_Bookcase_0.geometry}
										material={materials.Bookcase}
									/>
								</group>
								<group name="Metal_low">
									<mesh
										name="Metal_low_Bookcase_0"
										castShadow
										receiveShadow
										geometry={nodes.Metal_low_Bookcase_0.geometry}
										material={materials.Bookcase}
									/>
								</group>
								<group name="MetalRod_low">
									<mesh
										name="MetalRod_low_Bookcase_0"
										castShadow
										receiveShadow
										geometry={nodes.MetalRod_low_Bookcase_0.geometry}
										material={materials.Bookcase}
									/>
								</group>
								<group name="Prop1_low">
									<mesh
										name="Prop1_low_Bookcase_0"
										castShadow
										receiveShadow
										geometry={nodes.Prop1_low_Bookcase_0.geometry}
										material={materials.Bookcase}
									/>
								</group>
							</group>
							<group name="pPlane1">
								<mesh
									name="pPlane1_Extra_0"
									castShadow
									receiveShadow
									geometry={nodes.pPlane1_Extra_0.geometry}
									material={materials.Extra}
								/>
							</group>
						</group>
					</group>
				</group>

				{/* Blacksmith */}
				<Html position={[45, 20, 240]}>
					{discoveryText === "blacksmith" ? (
						<p
							className="w-[300px] p-4 text-[black] rounded-lg"
							style={{
								userSelect: "none",
								backgroundColor: "rgba(255, 255, 255, 0.6)",
							}}
						>
							I am a lover of MMROPG's such as Ultima Online, Everquest, World
							of Warcraft, and New World.
						</p>
					) : null}
				</Html>
				<group
					name="blacksmith_scene"
					position={[74.435, -1.5, 205]}
					rotation={[-Math.PI / 2, 0, 3.12]}
					scale={0.09}
					className="w-[300px] cursor-pointer rounded-lg"
					style={{ userSelect: "none" }}
					onPointerOver={() => {
						setHovered(true);
						setDiscoveryText("blacksmith");
						event.stopPropagation(); // Prevent event propagation
					}}
					onPointerOut={() => {
						setHovered(false);
						setDiscoveryText(null);
					}}
				>
					<group
						name="c51a6f22ccad4c4ca56e8ace1a6cf58ffbx"
						rotation={[Math.PI / 2, 0, 0]}
					>
						<group name="RootNode009">
							<group
								name="Anvil_low"
								position={[393.597, 79.625, 9.732]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Anvil_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Anvil_low_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="AxeHandle_low"
								position={[8.087, 121.981, 520.12]}
								rotation={[2.245, -1.186, 0.638]}
								scale={100}
							>
								<group name="Axe_low" position={[-0.008, -0.002, 0.58]}>
									<mesh
										name="Axe_low_WeaponsToolsMat_0"
										castShadow
										receiveShadow
										geometry={nodes.Axe_low_WeaponsToolsMat_0.geometry}
										material={materials.WeaponsToolsMat}
									/>
								</group>
								<mesh
									name="AxeHandle_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.AxeHandle_low_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="Bar2_low"
								position={[-18.489, 194.884, -167.423]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Bar2_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Bar2_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="Bar3_low"
								position={[-18.68, 194.197, -176.309]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Bar3_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Bar3_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="Barrel2_low"
								position={[295.896, 54.878, 384.654]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Barrel2_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Barrel2_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Barrel3_low"
								position={[295.896, 54.878, 384.654]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Barrel3_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Barrel3_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Barrel_low"
								position={[295.896, 54.878, 384.654]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Barrel_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Barrel_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Bed_low"
								position={[60.887, 122.185, 276.772]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Bed_low_FurnitureMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Bed_low_FurnitureMat_0.geometry}
									material={materials.FurnitureMat}
								/>
							</group>
							<group
								name="BedLegs_low"
								position={[179.67, 93.786, 230.561]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="BedLegs_low_FurnitureMat_0"
									castShadow
									receiveShadow
									geometry={nodes.BedLegs_low_FurnitureMat_0.geometry}
									material={materials.FurnitureMat}
								/>
							</group>
							<group
								name="Bellows_low"
								position={[276.206, 80.246, 144.413]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Bellows_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Bellows_low_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="Bench2_low"
								position={[323.14, 17.413, -229.912]}
								rotation={[-Math.PI / 2, 0, Math.PI / 2]}
								scale={100}
							>
								<mesh
									name="Bench2_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Bench2_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Bench_low"
								position={[323.241, 42.152, -229.988]}
								rotation={[-Math.PI / 2, 0, Math.PI / 2]}
								scale={100}
							>
								<mesh
									name="Bench_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Bench_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Blanket_low"
								position={[84.797, 136.378, 237.876]}
								rotation={[-Math.PI / 2, 0, 0.667]}
								scale={100}
							>
								<mesh
									name="Blanket_low_FurnitureMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Blanket_low_FurnitureMat_0.geometry}
									material={materials.FurnitureMat}
								/>
							</group>
							<group
								name="Board_low"
								position={[189.46, 244.481, -43.801]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Board_low_FurnitureMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Board_low_FurnitureMat_0.geometry}
									material={materials.FurnitureMat}
								/>
							</group>
							<group
								name="Books2_low"
								position={[61.891, 217.363, 324.881]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Books2_low_InteriorItemsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Books2_low_InteriorItemsMat_0.geometry}
									material={materials.InteriorItemsMat}
								/>
							</group>
							<group
								name="Books3_low"
								position={[61.891, 217.363, 324.881]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Books3_low_InteriorItemsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Books3_low_InteriorItemsMat_0.geometry}
									material={materials.InteriorItemsMat}
								/>
							</group>
							<group
								name="Books4_low"
								position={[61.891, 217.363, 324.881]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Books4_low_InteriorItemsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Books4_low_InteriorItemsMat_0.geometry}
									material={materials.InteriorItemsMat}
								/>
							</group>
							<group
								name="Books5_low"
								position={[61.891, 217.363, 324.881]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Books5_low_InteriorItemsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Books5_low_InteriorItemsMat_0.geometry}
									material={materials.InteriorItemsMat}
								/>
							</group>
							<group
								name="Books6_low"
								position={[61.891, 217.363, 324.881]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Books6_low_InteriorItemsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Books6_low_InteriorItemsMat_0.geometry}
									material={materials.InteriorItemsMat}
								/>
							</group>
							<group
								name="Books7_low"
								position={[61.891, 217.363, 324.881]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Books7_low_InteriorItemsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Books7_low_InteriorItemsMat_0.geometry}
									material={materials.InteriorItemsMat}
								/>
							</group>
							<group
								name="Books_low"
								position={[61.891, 217.363, 324.881]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Books_low_InteriorItemsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Books_low_InteriorItemsMat_0.geometry}
									material={materials.InteriorItemsMat}
								/>
							</group>
							<group
								name="Boots_low"
								position={[55.056, 83.693, 190.451]}
								scale={100}
							>
								<mesh
									name="Boots_low_InteriorItemsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Boots_low_InteriorItemsMat_0.geometry}
									material={materials.InteriorItemsMat}
								/>
							</group>
							<group
								name="Broom_low"
								position={[163.325, 103.046, -151.404]}
								rotation={[1.362, -0.281, 2.487]}
								scale={100}
							>
								<mesh
									name="Broom_low_InteriorItemsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Broom_low_InteriorItemsMat_0.geometry}
									material={materials.InteriorItemsMat}
								/>
							</group>
							<group
								name="BroomHandle_low"
								position={[179.645, 158.333, -163.143]}
								rotation={[1.362, -0.281, 2.487]}
								scale={100}
							>
								<mesh
									name="BroomHandle_low_InteriorItemsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.BroomHandle_low_InteriorItemsMat_0.geometry}
									material={materials.InteriorItemsMat}
								/>
							</group>
							<group
								name="Chair2_low"
								position={[-39.261, 120.091, 101.92]}
								rotation={[-Math.PI / 2, 0, Math.PI]}
								scale={100}
							>
								<mesh
									name="Chair2_low_FurnitureMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Chair2_low_FurnitureMat_0.geometry}
									material={materials.FurnitureMat}
								/>
							</group>
							<group
								name="Chair3_low"
								position={[-40.263, 120.091, 144.259]}
								rotation={[-Math.PI / 2, 0, Math.PI]}
								scale={100}
							>
								<mesh
									name="Chair3_low_FurnitureMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Chair3_low_FurnitureMat_0.geometry}
									material={materials.FurnitureMat}
								/>
							</group>
							<group
								name="Chair4_low"
								position={[-17.031, 170.715, 151.089]}
								rotation={[-1.423, 0, Math.PI]}
								scale={100}
							>
								<mesh
									name="Chair4_low_FurnitureMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Chair4_low_FurnitureMat_0.geometry}
									material={materials.FurnitureMat}
								/>
							</group>
							<group
								name="Chair_low"
								position={[-17.031, 128.186, 122.746]}
								rotation={[-Math.PI / 2, 0, Math.PI]}
								scale={100}
							>
								<mesh
									name="Chair_low_FurnitureMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Chair_low_FurnitureMat_0.geometry}
									material={materials.FurnitureMat}
								/>
							</group>
							<group
								name="Chest_low"
								position={[156.334, 110.665, -48.718]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Chest_low_FurnitureMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Chest_low_FurnitureMat_0.geometry}
									material={materials.FurnitureMat}
								/>
							</group>
							<group
								name="Clothing_low"
								position={[190.497, 177.195, 156.387]}
								rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
								scale={100}
							>
								<mesh
									name="Clothing_low_InteriorItemsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Clothing_low_InteriorItemsMat_0.geometry}
									material={materials.InteriorItemsMat}
								/>
							</group>
							<group
								name="Crate2_low"
								position={[357.743, 21.489, -157.676]}
								rotation={[-Math.PI / 2, 0, 0.221]}
								scale={100}
							>
								<mesh
									name="Crate2_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Crate2_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Crate_low"
								position={[277.535, 35.474, -122.286]}
								rotation={[-Math.PI / 2, 0, -0.193]}
								scale={100}
							>
								<mesh
									name="Crate_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Crate_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Door1_low"
								position={[134.919, 209.292, -193.375]}
								rotation={[-Math.PI / 2, 0, -2.098]}
								scale={100}
							>
								<group name="Bar_low" position={[-1.208, -0.104, -0.208]}>
									<mesh
										name="Bar_low_blacksmithsMat_0"
										castShadow
										receiveShadow
										geometry={nodes.Bar_low_blacksmithsMat_0.geometry}
										material={materials.blacksmithsMat}
									/>
								</group>
								<group name="Door11_low" position={[-0.469, 0.016, 0.357]}>
									<mesh
										name="Door11_low_blacksmithsMat_0"
										castShadow
										receiveShadow
										geometry={nodes.Door11_low_blacksmithsMat_0.geometry}
										material={materials.blacksmithsMat}
									/>
								</group>
								<group name="Door12_low" position={[-0.469, 0.016, -0.348]}>
									<mesh
										name="Door12_low_blacksmithsMat_0"
										castShadow
										receiveShadow
										geometry={nodes.Door12_low_blacksmithsMat_0.geometry}
										material={materials.blacksmithsMat}
									/>
								</group>
								<mesh
									name="Door1_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Door1_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="Door2_low"
								position={[134.919, 115.136, -193.375]}
								rotation={[-Math.PI / 2, 0, -2.098]}
								scale={100}
							>
								<group name="Door21_low" position={[-0.469, 0.016, 0.344]}>
									<mesh
										name="Door21_low_blacksmithsMat_0"
										castShadow
										receiveShadow
										geometry={nodes.Door21_low_blacksmithsMat_0.geometry}
										material={materials.blacksmithsMat}
									/>
								</group>
								<group name="Door22_low" position={[-0.469, 0.016, -0.344]}>
									<mesh
										name="Door22_low_blacksmithsMat_0"
										castShadow
										receiveShadow
										geometry={nodes.Door22_low_blacksmithsMat_0.geometry}
										material={materials.blacksmithsMat}
									/>
								</group>
								<mesh
									name="Door2_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Door2_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="DoorSupport_low"
								position={[61.865, 275.809, -181.146]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="DoorSupport_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.DoorSupport_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="FireIron_low"
								position={[245.404, 116.104, 211.658]}
								rotation={[-1.296, 0, 0]}
								scale={100}
							>
								<mesh
									name="FireIron_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.FireIron_low_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group name="Forge_low" scale={100}>
								<mesh
									name="Forge_low_ForgeMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Forge_low_ForgeMat_0.geometry}
									material={materials.ForgeMat}
								/>
							</group>
							<group
								name="GrearAxeHandle2_low"
								position={[456.65, 85.213, -205.449]}
								rotation={[-1.404, -0.187, 0.006]}
								scale={100}
							>
								<mesh
									name="GrearAxeHandle2_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={
										nodes.GrearAxeHandle2_low_WeaponsToolsMat_0.geometry
									}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="GreatAxe1_low"
								position={[447.79, 138.406, -137.815]}
								rotation={[-1.716, -0.153, 0]}
								scale={100}
							>
								<mesh
									name="GreatAxe1_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.GreatAxe1_low_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="GreatAxe2_low"
								position={[446.517, 137.336, -196.778]}
								rotation={[-1.404, -0.187, 0.006]}
								scale={100}
							>
								<mesh
									name="GreatAxe2_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.GreatAxe2_low_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="GreatAxeHandle1_low"
								position={[456.145, 84.962, -130.043]}
								rotation={[-1.716, -0.153, 0]}
								scale={100}
							>
								<mesh
									name="GreatAxeHandle1_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={
										nodes.GreatAxeHandle1_low_WeaponsToolsMat_0.geometry
									}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="GreatHammer_low"
								position={[439.558, 18.619, 61.754]}
								rotation={[1.171, 0.25, 0.973]}
								scale={100}
							>
								<mesh
									name="GreatHammer_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.GreatHammer_low_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="GreatHammerHandle_low"
								position={[418.461, 96.712, 29.027]}
								rotation={[1.171, 0.25, 0.973]}
								scale={100}
							>
								<mesh
									name="GreatHammerHandle_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={
										nodes.GreatHammerHandle_low_WeaponsToolsMat_0.geometry
									}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group name="Ground_high">
								<mesh
									name="Ground_high_GroundMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Ground_high_GroundMat_0.geometry}
									material={materials.GroundMat}
								/>
							</group>
							<group
								name="Hammer_low"
								position={[288.573, 68.086, 57.482]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Hammer_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Hammer_low_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="HammerHandle_low"
								position={[297.974, 67.51, 63.597]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="HammerHandle_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.HammerHandle_low_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="Hay_low"
								position={[101.256, 127.334, 226.055]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Hay_low_FurnitureMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Hay_low_FurnitureMat_0.geometry}
									material={materials.FurnitureMat}
								/>
							</group>
							<group
								name="HorseShoe_low"
								position={[231.686, 199.59, -97.289]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="HorseShoe_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.HorseShoe_low_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="HorseShoe_low001"
								position={[231.686, 199.59, 145.756]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="HorseShoe_low001_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.HorseShoe_low001_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="Ingot_low"
								position={[368.279, 13.619, -161.355]}
								rotation={[-Math.PI / 2, 0, 0.027]}
								scale={100}
							>
								<mesh
									name="Ingot_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Ingot_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Ingot_low001"
								position={[346.188, 13.619, -156.775]}
								rotation={[-Math.PI / 2, 0, 0.119]}
								scale={100}
							>
								<mesh
									name="Ingot_low001_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Ingot_low001_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Ingot_low002"
								position={[358.88, 23.669, -156.775]}
								rotation={[-Math.PI / 2, 0, -1.508]}
								scale={100}
							>
								<mesh
									name="Ingot_low002_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Ingot_low002_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Ladder2_low"
								position={[-127.46, 48.116, -112.905]}
								rotation={[-1.589, 0.3, 0]}
								scale={100}
							>
								<mesh
									name="Ladder2_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Ladder2_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Ladder_low"
								position={[-127.354, 51.096, 72.998]}
								rotation={[-1.589, 0.3, 0]}
								scale={100}
							>
								<mesh
									name="Ladder_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Ladder_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Log1_low"
								position={[43.693, 22.664, 411.045]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Log1_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Log1_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Log1_low001"
								position={[122.757, 22.664, 409.136]}
								rotation={[Math.PI / 2, 0.392, Math.PI]}
								scale={100}
							>
								<mesh
									name="Log1_low001_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Log1_low001_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Log1_low002"
								position={[103.109, 49.617, 414.44]}
								rotation={[1.571, -1.563, 3.142]}
								scale={100}
							>
								<mesh
									name="Log1_low002_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Log1_low002_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Log1_low003"
								position={[23.049, 49.617, 404.698]}
								rotation={[Math.PI / 2, -0.082, Math.PI]}
								scale={100}
							>
								<mesh
									name="Log1_low003_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Log1_low003_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Log1_low004"
								position={[83.577, 76.133, 406.951]}
								rotation={[-Math.PI / 2, 0.209, 0]}
								scale={100}
							>
								<mesh
									name="Log1_low004_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Log1_low004_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Log2_low"
								position={[3.917, 22.664, 412.943]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Log2_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Log2_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Log2_low001"
								position={[82.98, 22.664, 411.338]}
								rotation={[Math.PI / 2, -1.15, -Math.PI]}
								scale={100}
							>
								<mesh
									name="Log2_low001_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Log2_low001_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Log2_low002"
								position={[63.332, 49.617, 410.036]}
								rotation={[-Math.PI / 2, 0.522, 0]}
								scale={100}
							>
								<mesh
									name="Log2_low002_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Log2_low002_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Log2_low003"
								position={[43.755, 76.682, 405.631]}
								rotation={[Math.PI / 2, -0.449, -Math.PI]}
								scale={100}
							>
								<mesh
									name="Log2_low003_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Log2_low003_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Mug_low"
								position={[-3.901, 172.014, 27.495]}
								rotation={[-Math.PI / 2, 0, 0.292]}
								scale={100}
							>
								<group
									name="Mug2_low"
									position={[0.139, 0.065, 0.068]}
									rotation={[0, 0, 0.436]}
								>
									<mesh
										name="Mug2_low_InteriorItemsMat_0"
										castShadow
										receiveShadow
										geometry={nodes.Mug2_low_InteriorItemsMat_0.geometry}
										material={materials.InteriorItemsMat}
									/>
								</group>
								<group
									name="Mug3_low"
									position={[0.139, 0.065, -0.066]}
									rotation={[0, 0, 0.436]}
								>
									<mesh
										name="Mug3_low_InteriorItemsMat_0"
										castShadow
										receiveShadow
										geometry={nodes.Mug3_low_InteriorItemsMat_0.geometry}
										material={materials.InteriorItemsMat}
									/>
								</group>
								<group
									name="Mug4_low"
									position={[0.175, 0.078, 0.001]}
									rotation={[0, 0, 0.436]}
								>
									<mesh
										name="Mug4_low_InteriorItemsMat_0"
										castShadow
										receiveShadow
										geometry={nodes.Mug4_low_InteriorItemsMat_0.geometry}
										material={materials.InteriorItemsMat}
									/>
								</group>
								<mesh
									name="Mug_low_InteriorItemsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Mug_low_InteriorItemsMat_0.geometry}
									material={materials.InteriorItemsMat}
								/>
							</group>
							<group
								name="Peg2_low"
								position={[196.561, 241.801, 13.582]}
								rotation={[-Math.PI / 2, 0, -Math.PI]}
								scale={100}
							>
								<mesh
									name="Peg2_low_InteriorItemsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Peg2_low_InteriorItemsMat_0.geometry}
									material={materials.InteriorItemsMat}
								/>
							</group>
							<group
								name="Peg3_low"
								position={[196.561, 239.609, -82.303]}
								rotation={[-Math.PI / 2, 0, -Math.PI]}
								scale={100}
							>
								<mesh
									name="Peg3_low_InteriorItemsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Peg3_low_InteriorItemsMat_0.geometry}
									material={materials.InteriorItemsMat}
								/>
							</group>
							<group
								name="Peg_low"
								position={[197.519, 238.129, 156.319]}
								rotation={[Math.PI / 2, 0, Math.PI]}
								scale={100}
							>
								<mesh
									name="Peg_low_InteriorItemsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Peg_low_InteriorItemsMat_0.geometry}
									material={materials.InteriorItemsMat}
								/>
							</group>
							<group
								name="Peg_low001"
								position={[222.385, 207.087, -97.626]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Peg_low001_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Peg_low001_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Peg_low002"
								position={[222.385, 207.087, 145.418]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Peg_low002_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Peg_low002_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Pillow_low"
								position={[-35.788, 138.976, 273.472]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Pillow_low_FurnitureMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Pillow_low_FurnitureMat_0.geometry}
									material={materials.FurnitureMat}
								/>
							</group>
							<group
								name="Planks2_low"
								position={[52.985, 348.654, -196.074]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Planks2_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Planks2_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="Planks_low"
								position={[402.088, 274.671, 80.102]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Planks_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Planks_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="Roof_low"
								position={[-46.481, 372.209, 79.974]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Roof_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Roof_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="RoofSupport2_low"
								position={[429.256, 93.682, 79.973]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="RoofSupport2_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.RoofSupport2_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="RoofSupport3_low"
								position={[146.408, 377.68, -203.933]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="RoofSupport3_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.RoofSupport3_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="RoofSupport4_low"
								position={[453.465, 283.272, 79.973]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="RoofSupport4_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.RoofSupport4_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="RoofSupport5_low"
								position={[455.669, 251.253, 79.974]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="RoofSupport5_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.RoofSupport5_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="RoofSupport6_low"
								position={[-50.215, 377.68, -202.164]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="RoofSupport6_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.RoofSupport6_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="RoofSupport7_low"
								position={[49.353, 402.901, 80.102]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="RoofSupport7_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.RoofSupport7_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="RoofSupport8_low"
								position={[60.914, 345.116, 80.102]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="RoofSupport8_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.RoofSupport8_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="RoofSupport9_low"
								position={[-119.54, 341.669, 79.974]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="RoofSupport9_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.RoofSupport9_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="RoofSupport_low"
								position={[60.914, 160.86, 80.103]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="RoofSupport_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.RoofSupport_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="Rope_low"
								position={[451.527, 270.125, -228.934]}
								rotation={[Math.PI, 0, 1.418]}
								scale={100}
							>
								<mesh
									name="Rope_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Rope_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="Sack2_low"
								position={[-31.024, 78.315, -112.669]}
								rotation={[3.038, 0.468, 0.016]}
								scale={100}
							>
								<mesh
									name="Sack2_low_InteriorItemsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Sack2_low_InteriorItemsMat_0.geometry}
									material={materials.InteriorItemsMat}
								/>
							</group>
							<group
								name="Sack_low"
								position={[-56.252, 106.96, -151.837]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Sack_low_InteriorItemsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Sack_low_InteriorItemsMat_0.geometry}
									material={materials.InteriorItemsMat}
								/>
							</group>
							<group
								name="Shelf2_low"
								position={[149.519, 197.305, 331.661]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Shelf2_low_FurnitureMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Shelf2_low_FurnitureMat_0.geometry}
									material={materials.FurnitureMat}
								/>
							</group>
							<group
								name="Shelf_low"
								position={[64.575, 204.426, 316.927]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Shelf_low_FurnitureMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Shelf_low_FurnitureMat_0.geometry}
									material={materials.FurnitureMat}
								/>
							</group>
							<group
								name="Shield_low"
								position={[460.024, 50.514, 321.559]}
								rotation={[-1.475, -0.3, -0.288]}
								scale={100}
							>
								<mesh
									name="Shield_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Shield_low_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="Sign2_low"
								position={[453.586, 194.056, 237.622]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Sign2_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Sign2_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Sign3_low"
								position={[454.089, 236.484, 207.21]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Sign3_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Sign3_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Sign_low"
								position={[453.689, 196.327, 237.488]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Sign_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Sign_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Spear2_low"
								position={[269.422, 112.747, -13.671]}
								rotation={[-1.685, 0.079, 0.009]}
								scale={100}
							>
								<mesh
									name="Spear2_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Spear2_low_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="Spear_low"
								position={[254.898, 115.738, -3.863]}
								rotation={[-1.472, -0.088, -0.527]}
								scale={100}
							>
								<mesh
									name="Spear_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Spear_low_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="Stairs_low"
								position={[61.499, 34.556, -239.056]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Stairs_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Stairs_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="StumpAnvil_low"
								position={[389.454, 60.084, 9.23]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="StumpAnvil_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.StumpAnvil_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="StumpWoodcutter_low"
								position={[-50.499, 45.673, 509.552]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="StumpWoodcutter_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={
										nodes.StumpWoodcutter_low_WoodExteriorMat_0.geometry
									}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Swordblade_low"
								position={[474.032, 51.089, -160.47]}
								rotation={[-1.428, -0.431, 0]}
								scale={100}
							>
								<mesh
									name="Swordblade_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Swordblade_low_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="Swordblade_low002"
								position={[194.737, 245.65, -53.902]}
								rotation={[0, 0.003, -0.09]}
								scale={100}
							>
								<mesh
									name="Swordblade_low002_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Swordblade_low002_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="SwordGuard_low"
								position={[448.327, 106.495, -152.488]}
								rotation={[-1.428, -0.431, 0]}
								scale={100}
							>
								<mesh
									name="SwordGuard_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.SwordGuard_low_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="SwordGuard_low002"
								position={[194.954, 245.624, 7.695]}
								rotation={[0, 0.003, -0.09]}
								scale={100}
							>
								<mesh
									name="SwordGuard_low002_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.SwordGuard_low002_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="SwordHilt_low"
								position={[438.516, 127.671, -149.518]}
								rotation={[-1.428, -0.431, 0]}
								scale={100}
							>
								<mesh
									name="SwordHilt_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.SwordHilt_low_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="SwordHilt_low002"
								position={[195.051, 245.694, 31.221]}
								rotation={[0, 0.003, -0.09]}
								scale={100}
							>
								<mesh
									name="SwordHilt_low002_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.SwordHilt_low002_WeaponsToolsMat_0.geometry}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="SwordShortBlade_low"
								position={[270.948, 28.003, -122.348]}
								rotation={[-1.15, -0.449, 0.676]}
								scale={100}
							>
								<mesh
									name="SwordShortBlade_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={
										nodes.SwordShortBlade_low_WeaponsToolsMat_0.geometry
									}
									material={materials.WeaponsToolsMat}
								/>
								<group name="SwordShortGuard_low" position={[0, 0, 0.579]}>
									<mesh
										name="SwordShortGuard_low_WeaponsToolsMat_0"
										castShadow
										receiveShadow
										geometry={
											nodes.SwordShortGuard_low_WeaponsToolsMat_0.geometry
										}
										material={materials.WeaponsToolsMat}
									/>
								</group>
								<group name="SwordShortHilt_low" position={[0, 0.001, 0.8]}>
									<mesh
										name="SwordShortHilt_low_WeaponsToolsMat_0"
										castShadow
										receiveShadow
										geometry={
											nodes.SwordShortHilt_low_WeaponsToolsMat_0.geometry
										}
										material={materials.WeaponsToolsMat}
									/>
								</group>
							</group>
							<group
								name="SwordShortBlade_low001"
								position={[282.758, 26.663, -119.252]}
								rotation={[-1.89, -0.554, -0.379]}
								scale={100}
							>
								<mesh
									name="SwordShortBlade_low001_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={
										nodes.SwordShortBlade_low001_WeaponsToolsMat_0.geometry
									}
									material={materials.WeaponsToolsMat}
								/>
								<group name="SwordShortGuard_low001" position={[0, 0, 0.579]}>
									<mesh
										name="SwordShortGuard_low001_WeaponsToolsMat_0"
										castShadow
										receiveShadow
										geometry={
											nodes.SwordShortGuard_low001_WeaponsToolsMat_0.geometry
										}
										material={materials.WeaponsToolsMat}
									/>
								</group>
								<group name="SwordShortHilt_low001" position={[0, 0.001, 0.8]}>
									<mesh
										name="SwordShortHilt_low001_WeaponsToolsMat_0"
										castShadow
										receiveShadow
										geometry={
											nodes.SwordShortHilt_low001_WeaponsToolsMat_0.geometry
										}
										material={materials.WeaponsToolsMat}
									/>
								</group>
							</group>
							<group
								name="SwordShortBlade_low002"
								position={[273.659, 28.435, -129.374]}
								rotation={[-1.862, 0.61, -2.666]}
								scale={100}
							>
								<mesh
									name="SwordShortBlade_low002_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={
										nodes.SwordShortBlade_low002_WeaponsToolsMat_0.geometry
									}
									material={materials.WeaponsToolsMat}
								/>
								<group name="SwordShortGuard_low002" position={[0, 0, 0.579]}>
									<mesh
										name="SwordShortGuard_low002_WeaponsToolsMat_0"
										castShadow
										receiveShadow
										geometry={
											nodes.SwordShortGuard_low002_WeaponsToolsMat_0.geometry
										}
										material={materials.WeaponsToolsMat}
									/>
								</group>
								<group name="SwordShortHilt_low002" position={[0, 0.001, 0.8]}>
									<mesh
										name="SwordShortHilt_low002_WeaponsToolsMat_0"
										castShadow
										receiveShadow
										geometry={
											nodes.SwordShortHilt_low002_WeaponsToolsMat_0.geometry
										}
										material={materials.WeaponsToolsMat}
									/>
								</group>
							</group>
							<group
								name="SwordShortPommel_low"
								position={[235.12, 95.795, -91.985]}
								rotation={[-2.225, 0.779, 0.915]}
								scale={100}
							>
								<mesh
									name="SwordShortPommel_low_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={
										nodes.SwordShortPommel_low_WeaponsToolsMat_0.geometry
									}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="SwordShortPommel_low001"
								position={[239.368, 93.235, -141.31]}
								rotation={[-1.242, 0.911, -0.539]}
								scale={100}
							>
								<mesh
									name="SwordShortPommel_low001_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={
										nodes.SwordShortPommel_low001_WeaponsToolsMat_0.geometry
									}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="SwordShortPommel_low002"
								position={[320.948, 93.161, -148.752]}
								rotation={[-1.129, -0.816, -2.562]}
								scale={100}
							>
								<mesh
									name="SwordShortPommel_low002_WeaponsToolsMat_0"
									castShadow
									receiveShadow
									geometry={
										nodes.SwordShortPommel_low002_WeaponsToolsMat_0.geometry
									}
									material={materials.WeaponsToolsMat}
								/>
							</group>
							<group
								name="Table2_low"
								position={[23.89, 150.874, 6.782]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Table2_low_FurnitureMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Table2_low_FurnitureMat_0.geometry}
									material={materials.FurnitureMat}
								/>
							</group>
							<group
								name="Table3_low"
								position={[-26.638, 151.737, 45.893]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Table3_low_FurnitureMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Table3_low_FurnitureMat_0.geometry}
									material={materials.FurnitureMat}
								/>
							</group>
							<group
								name="Table_low"
								position={[-18.179, 158.872, 46.274]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Table_low_FurnitureMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Table_low_FurnitureMat_0.geometry}
									material={materials.FurnitureMat}
								/>
							</group>
							<group
								name="Vase_low"
								position={[262.22, 85.445, -9.438]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="Vase_low_ForgeMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Vase_low_ForgeMat_0.geometry}
									material={materials.ForgeMat}
								/>
							</group>
							<group name="Wall_low" scale={100}>
								<mesh
									name="Wall_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Wall_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="WeaponStand2_low"
								position={[437.955, 57.327, -163.157]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="WeaponStand2_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.WeaponStand2_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="WeaponStand_low"
								position={[447.739, 92.645, -162.911]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="WeaponStand_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.WeaponStand_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="WeaponStandRope2_low"
								position={[442.407, 92.437, -213.01]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="WeaponStandRope2_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={
										nodes.WeaponStandRope2_low_WoodExteriorMat_0.geometry
									}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="WeaponStandRope_low"
								position={[441.639, 92.311, -113.599]}
								rotation={[-Math.PI / 2, 0.192, 0]}
								scale={100}
							>
								<mesh
									name="WeaponStandRope_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={
										nodes.WeaponStandRope_low_WoodExteriorMat_0.geometry
									}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Wheel2_low"
								position={[451.665, 53.971, 370.561]}
								rotation={[-1.998, 0.134, 2.075]}
								scale={100}
							>
								<mesh
									name="Wheel2_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Wheel2_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="Wheel_low"
								position={[451.665, 53.971, 370.561]}
								rotation={[-1.872, -0.095, 2.073]}
								scale={[100.357, 101.538, 101.696]}
							>
								<mesh
									name="Wheel_low_WoodExteriorMat_0"
									castShadow
									receiveShadow
									geometry={nodes.Wheel_low_WoodExteriorMat_0.geometry}
									material={materials.WoodExteriorMat}
								/>
							</group>
							<group
								name="WindowRail2_low"
								position={[-71.751, 205.723, 109.434]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="WindowRail2_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.WindowRail2_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="WindowRail_low"
								position={[-71.951, 205.723, 50.528]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="WindowRail_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.WindowRail_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="WindowRailing_low"
								position={[-71.147, 205.444, 80.862]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="WindowRailing_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.WindowRailing_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="WindowSupport2_low"
								position={[60.267, 242.116, 344.522]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="WindowSupport2_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.WindowSupport2_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="WindowSupport_low"
								position={[60.267, 242.116, 344.522]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="WindowSupport_low_blacksmithsMat_0"
									castShadow
									receiveShadow
									geometry={nodes.WindowSupport_low_blacksmithsMat_0.geometry}
									material={materials.blacksmithsMat}
								/>
							</group>
							<group
								name="WorkbenchStone_low"
								position={[286.779, 113.192, 247.543]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="WorkbenchStone_low_ForgeMat_0"
									castShadow
									receiveShadow
									geometry={nodes.WorkbenchStone_low_ForgeMat_0.geometry}
									material={materials.ForgeMat}
								/>
							</group>
							<group
								name="WorkbenchWood_low"
								position={[267.963, 58.451, 111.068]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									name="WorkbenchWood_low_ForgeMat_0"
									castShadow
									receiveShadow
									geometry={nodes.WorkbenchWood_low_ForgeMat_0.geometry}
									material={materials.ForgeMat}
								/>
							</group>
						</group>
					</group>
				</group>

				{/* Reading Corner */}
				<Html position={[90, 45, -350]}>
					{discoveryText === "reading-corner" ? (
						<p
							className="w-[300px] p-4 text-[black] rounded-lg"
							style={{
								userSelect: "none",
								backgroundColor: "rgba(255, 255, 255, 0.6)",
							}}
						>
							I'm an avid reader and I am currently enjoying the book "What's
							Our Problem" by Tim Urban.
						</p>
					) : null}
				</Html>
				<group
					name="rading_corner"
					position={[126.327, -4, -331.377]}
					rotation={[-Math.PI / 2, 0, -1.185]}
					scale={12}
					className="w-[300px] cursor-pointer rounded-lg"
					style={{ userSelect: "none" }}
					onPointerOver={() => {
						setHovered(true);
						setDiscoveryText("reading-corner");
						event.stopPropagation(); // Prevent event propagation
					}}
					onPointerOut={() => {
						setHovered(false);
						setDiscoveryText(null);
					}}
				>
					<group name="root002">
						<group name="GLTF_SceneRootNode002" rotation={[Math.PI / 2, 0, 0]}>
							<group
								name="armchair_low001_0"
								position={[0, 0.002, 0]}
								rotation={[0, -0.545, 0]}
							>
								<mesh
									name="Object_4005"
									castShadow
									receiveShadow
									geometry={nodes.Object_4005.geometry}
									material={materials.armchair}
								/>
							</group>
							<group
								name="book002_3"
								position={[-0.31, 0.555, -1.111]}
								rotation={[0, 0, -0.248]}
							>
								<mesh
									name="Object_10002"
									castShadow
									receiveShadow
									geometry={nodes.Object_10002.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book003_4"
								position={[-0.42, 0.555, -1.164]}
								rotation={[0, 0, -0.271]}
							>
								<mesh
									name="Object_12001"
									castShadow
									receiveShadow
									geometry={nodes.Object_12001.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book004_5"
								position={[-1.058, 0.554, -1.121]}
								rotation={[0, 0, 0.046]}
							>
								<mesh
									name="Object_14001"
									castShadow
									receiveShadow
									geometry={nodes.Object_14001.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book005_6"
								position={[-0.265, 1.025, -1.131]}
								scale={0.912}
							>
								<mesh
									name="Object_16001"
									castShadow
									receiveShadow
									geometry={nodes.Object_16001.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book006_7"
								position={[-0.357, 1.012, -1.12]}
								scale={0.846}
							>
								<mesh
									name="Object_18"
									castShadow
									receiveShadow
									geometry={nodes.Object_18.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book012_8"
								position={[-0.731, 0.404, -1.153]}
								rotation={[0, 0.136, -Math.PI / 2]}
							>
								<mesh
									name="Object_20"
									castShadow
									receiveShadow
									geometry={nodes.Object_20.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book013_9"
								position={[-0.724, 0.503, -1.153]}
								rotation={[Math.PI, -0.359, Math.PI / 2]}
								scale={[1, 0.871, 0.871]}
							>
								<mesh
									name="Object_22"
									castShadow
									receiveShadow
									geometry={nodes.Object_22.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book014_10"
								position={[-0.464, 1.002, -1.153]}
								scale={[1.198, 0.785, 0.912]}
							>
								<mesh
									name="Object_24"
									castShadow
									receiveShadow
									geometry={nodes.Object_24.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book015_11"
								position={[-0.575, 1.035, -1.111]}
								scale={0.95}
							>
								<mesh
									name="Object_26"
									castShadow
									receiveShadow
									geometry={nodes.Object_26.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book016_12"
								position={[-0.695, 1.031, -1.153]}
								rotation={[0, 0, -0.144]}
								scale={0.914}
							>
								<mesh
									name="Object_28"
									castShadow
									receiveShadow
									geometry={nodes.Object_28.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group name="book017_13" position={[-1.058, 1.517, -1.153]}>
								<mesh
									name="Object_30"
									castShadow
									receiveShadow
									geometry={nodes.Object_30.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book018_14"
								position={[-0.865, 1.489, -1.12]}
								rotation={[0, 0, 0.034]}
								scale={0.846}
							>
								<mesh
									name="Object_32"
									castShadow
									receiveShadow
									geometry={nodes.Object_32.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book019_15"
								position={[-0.959, 1.502, -1.164]}
								scale={0.921}
							>
								<mesh
									name="Object_34"
									castShadow
									receiveShadow
									geometry={nodes.Object_34.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book020_16"
								position={[-0.432, 1.376, -1.093]}
								rotation={[0, 0.428, Math.PI / 2]}
							>
								<mesh
									name="Object_36"
									castShadow
									receiveShadow
									geometry={nodes.Object_36.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book021_18"
								position={[-0.41, 1.485, -1.102]}
								rotation={[0, 0.727, -Math.PI / 2]}
								scale={[1.175, 1, 1]}
							>
								<mesh
									name="Object_40"
									castShadow
									receiveShadow
									geometry={nodes.Object_40.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book022_17"
								position={[-0.917, 0.893, -1.164]}
								rotation={[-Math.PI, 1.317, Math.PI / 2]}
							>
								<mesh
									name="Object_38"
									castShadow
									receiveShadow
									geometry={nodes.Object_38.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book023_20"
								position={[-0.713, 0.053, -0.055]}
								rotation={[0, -0.423, -Math.PI / 2]}
							>
								<mesh
									name="Object_44"
									castShadow
									receiveShadow
									geometry={nodes.Object_44.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book024_23"
								position={[-0.706, 0.156, -0.117]}
								rotation={[Math.PI, -0.469, Math.PI / 2]}
							>
								<mesh
									name="Object_50"
									castShadow
									receiveShadow
									geometry={nodes.Object_50.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book025_19"
								position={[-0.694, 0.438, -0.072]}
								rotation={[-Math.PI, 1.394, Math.PI / 2]}
								scale={[1.24, 1, 1]}
							>
								<mesh
									name="Object_42"
									castShadow
									receiveShadow
									geometry={nodes.Object_42.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book026_21"
								position={[-0.626, 0.252, -0.102]}
								rotation={[0, 1.087, -Math.PI / 2]}
								scale={[0.859, 1, 1]}
							>
								<mesh
									name="Object_46"
									castShadow
									receiveShadow
									geometry={nodes.Object_46.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book027_22"
								position={[-0.668, 0.335, -0.039]}
								rotation={[0, 0.671, -Math.PI / 2]}
								scale={[0.765, 0.914, 0.914]}
							>
								<mesh
									name="Object_48"
									castShadow
									receiveShadow
									geometry={nodes.Object_48.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book028_24"
								position={[0.351, 0.032, 0.646]}
								rotation={[0, 1.043, -Math.PI / 2]}
								scale={[0.592, 1, 1]}
							>
								<mesh
									name="Object_52"
									castShadow
									receiveShadow
									geometry={nodes.Object_52.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book029_25"
								position={[0.35, 0.097, 0.609]}
								rotation={[0, 0.727, -Math.PI / 2]}
								scale={[0.703, 0.865, 0.865]}
							>
								<mesh
									name="Object_54"
									castShadow
									receiveShadow
									geometry={nodes.Object_54.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group
								name="book030_26"
								position={[-0.773, 0.218, -1.616]}
								rotation={[0.193, Math.PI / 2, 0]}
								scale={[0.993, 1.087, 1.087]}
							>
								<mesh
									name="Object_56"
									castShadow
									receiveShadow
									geometry={nodes.Object_56.geometry}
									material={materials["book-green"]}
								/>
							</group>
							<group name="carpet_1" position={[-0.363, 0, -0.713]} />
							<group
								name="Cylinder002_27"
								position={[-0.713, 0.503, -0.047]}
								rotation={[0, -0.229, 0]}
							>
								<mesh
									name="Object_58"
									castShadow
									receiveShadow
									geometry={nodes.Object_58.geometry}
									material={materials.candle}
								/>
								<mesh
									name="Object_59"
									castShadow
									receiveShadow
									geometry={nodes.Object_59.geometry}
									material={materials.wick}
								/>
							</group>
							<group
								name="flame_28"
								position={[-0.713, 0.631, -0.05]}
								scale={1.476}
							>
								<mesh
									name="mesh_28"
									castShadow
									receiveShadow
									geometry={nodes.mesh_28.geometry}
									material={materials.flame}
									morphTargetDictionary={nodes.mesh_28.morphTargetDictionary}
									morphTargetInfluences={nodes.mesh_28.morphTargetInfluences}
								/>
							</group>
							<group name="shelf_2" position={[-0.666, -0.009, -0.965]}>
								<mesh
									name="Object_8002"
									castShadow
									receiveShadow
									geometry={nodes.Object_8002.geometry}
									material={materials["book-green"]}
								/>
							</group>
						</group>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/genericPOIPruned.glb");
