/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Land(props) {
	const { nodes, materials } = useGLTF("/land.glb");
	return (
		<group {...props} dispose={null}>
			{/* Mailbox */}
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube052.geometry}
				material={materials.Mailbox}
				position={[20.969, -1, -36.302]}
				rotation={[Math.PI, -1.217, Math.PI]}
				scale={0.75}
			/>
			{/* LinkedIn */}
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Curve.geometry}
				material={materials["Blue Rocks"]}
				position={[22.914, -1, -35.016]}
				rotation={[1.576, -0.013, 0.349]}
				scale={7.591}
			/>
			{/* House */}
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Icosphere006.geometry}
				material={materials.House}
				position={[0, -1, 0]}
				rotation={[0.014, 0.767, -0.025]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube046.geometry}
				material={materials.Billboard}
				position={[44.045, -1, -2.517]}
				rotation={[0, -1.45, 0]}
				scale={1.5}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube047.geometry}
				material={materials["Portrait Billboard"]}
				position={[38.757, -1, 5.412]}
				rotation={[-Math.PI, 0.55, -Math.PI]}
				scale={1.25}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube048.geometry}
				material={materials["Portrait Billboard"]}
				position={[31.207, -1, 5.479]}
				rotation={[-Math.PI, 0.554, -Math.PI]}
				scale={1.25}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube049.geometry}
				material={materials["Portrait Billboard"]}
				position={[38.17, -1, -7.218]}
				rotation={[Math.PI, -0.66, Math.PI]}
				scale={1.25}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube050.geometry}
				material={materials["Portrait Billboard"]}
				position={[31.496, -1, -7.324]}
				rotation={[Math.PI, -0.493, Math.PI]}
				scale={1.25}
			/>
		</group>
	);
}

useGLTF.preload("/land.glb");
