/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function LargeTerrain(props) {
	const { nodes, materials } = useGLTF("/Terrain_Forest_A_glb.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.mesh_0.geometry}
				material={nodes.mesh_0.material}
			/>
		</group>
	);
}

useGLTF.preload("/Terrain_Forest_A_glb.glb");
