/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function NewScene(props) {
	const { nodes, materials } = useGLTF("/new-scene.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_10.geometry}
					material={materials["standard.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_11.geometry}
					material={materials["standard.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_12.geometry}
					material={materials["stone.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_14.geometry}
					material={materials["window_bar.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_15.geometry}
					material={materials["windowemiisive-8355712.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_4.geometry}
					material={materials["House_wall-8355712.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_5.geometry}
					material={materials["MainWood.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_7.geometry}
					material={materials["grass.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_8.geometry}
					material={materials["roof-8355712.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_9.geometry}
					material={materials["roofunderwood-8355712.001"]}
				/>
			</group>
			<group
				position={[-61.345, 0, 27.096]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={13.614}
			>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01_leafes_Mat001_0.geometry}
						material={materials["leafes_Mat.001"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01_leafes_Mat001_0001.geometry}
						material={materials["leafes_Mat.001"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01001_trunk_Mat001_0.geometry}
						material={materials["trunk_Mat.001"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01001_trunk_Mat001_0001.geometry}
						material={materials["trunk_Mat.001"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01001_trunk_Mat001_0002.geometry}
						material={materials["trunk_Mat.001"]}
					/>
				</group>
			</group>
			<group
				position={[-66.037, 0, 54.918]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={13.614}
			>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01_leafes_Mat001_0002.geometry}
						material={materials["leafes_Mat.001"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01_leafes_Mat001_0003.geometry}
						material={materials["leafes_Mat.001"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01001_trunk_Mat001_0003.geometry}
						material={materials["trunk_Mat.001"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01001_trunk_Mat001_0004.geometry}
						material={materials["trunk_Mat.001"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01001_trunk_Mat001_0005.geometry}
						material={materials["trunk_Mat.001"]}
					/>
				</group>
			</group>
			<group
				position={[-0.238, 1.089, 40.299]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.36}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_10001.geometry}
					material={materials.lambert9SG}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_2.geometry}
					material={materials.blinn1SG}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_4001.geometry}
					material={materials.lambert10SG}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_5001.geometry}
					material={materials.lambert11SG}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_6001.geometry}
					material={materials.lambert12SG}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_7001.geometry}
					material={materials.lambert2SG}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_8001.geometry}
					material={materials.lambert7SG}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_9001.geometry}
					material={materials.lambert8SG}
				/>
			</group>
			<group position={[-3.955, 0, 0.261]} rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Bottom_01_LP_Bottom_0.geometry}
						material={materials.Bottom}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Bottom_02_LP_Bottom_0.geometry}
						material={materials.Bottom}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Bottom_03_LP_Bottom_0.geometry}
						material={materials.Bottom}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Bottom_04_LP_Bottom_0.geometry}
						material={materials.Bottom}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Bottom_05_LP_Bottom_0.geometry}
						material={materials.Bottom}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Bottom_06_LP_Bottom_0.geometry}
						material={materials.Bottom}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Bottom_07_LP_Bottom_0.geometry}
						material={materials.Bottom}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cloth_01_LP_DetailsCloth_0.geometry}
						material={materials.DetailsCloth}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Details_01_LP_DetailsCloth_0.geometry}
						material={materials.DetailsCloth}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Top_01_LP_Top_0.geometry}
						material={materials["material.001"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Top_02_LP_Top_0.geometry}
						material={materials["material.001"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Top_03_LP_Top_0.geometry}
						material={materials["material.001"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Top_04_LP_Top_0.geometry}
						material={materials["material.001"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Top_05_LP_Top_0.geometry}
						material={materials["material.001"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Top_06_LP_Top_0.geometry}
						material={materials["material.001"]}
					/>
				</group>
			</group>
			<group
				position={[-66.021, 0.038, 42.522]}
				rotation={[-Math.PI, 1.558, -Math.PI]}
				scale={2.542}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane1313.geometry}
					material={materials.Foliage_MAT}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane1313_1.geometry}
					material={materials.Water_MAT}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Base.geometry}
				material={materials.Base_Base_MAT}
				position={[-65.491, 0.169, 42.667]}
				rotation={[-Math.PI, 1.558, -Math.PI]}
				scale={2.542}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Railling.geometry}
				material={materials.Base_Base_MAT}
				position={[-65.491, 0.169, 42.667]}
				rotation={[-Math.PI, 1.558, -Math.PI]}
				scale={2.542}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Corners.geometry}
				material={materials.Base_SideRocks_MAT}
				position={[-65.491, -0.031, 42.667]}
				rotation={[-Math.PI, 1.558, -Math.PI]}
				scale={2.542}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Rocks1.geometry}
				material={materials.Base_SideRocks_MAT}
				position={[-65.491, -0.031, 42.667]}
				rotation={[-Math.PI, 1.558, -Math.PI]}
				scale={2.542}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Rocks2.geometry}
				material={materials.Base_SideRocks_MAT}
				position={[-65.491, -0.031, 42.667]}
				rotation={[-Math.PI, 1.558, -Math.PI]}
				scale={2.542}
			/>
			<group
				position={[-30.012, 0.253, 80.406]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={20.102}
			>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<group scale={0.01}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.One_LP_One_Mat_0.geometry}
							material={materials.One_Mat}
							position={[0, 0, -1.624]}
							scale={3.1}
						/>
					</group>
				</group>
			</group>
			<group
				position={[-36.219, 0, 80.228]}
				rotation={[-Math.PI, 0, 0]}
				scale={2.823}
			>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.defaultMaterial.geometry}
						material={materials.EYES}
						position={[0, 0, 0.548]}
						rotation={[1.243, 1.521, 0.382]}
					/>
				</group>
			</group>
			<group position={[-48.872, 0, 99.375]} rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<group position={[0, 0, -0.001]}>
						<group
							position={[352.443, 5.024, 614.977]}
							rotation={[0, 0, Math.PI]}
							scale={[30.335, 25.973, 30.335]}
						>
							<group position={[0, -1.429, 0]}>
								<mesh
									castShadow
									receiveShadow
									geometry={nodes["Platform_Low_Material_#111_0"].geometry}
									material={materials.Material_111}
									position={[-64.181, -5.266, -84.132]}
									scale={4.432}
								/>
							</group>
						</group>
					</group>
				</group>
			</group>
			<group position={[0, 0, 72.2]} rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
					<group
						position={[-535.251, 48.15, -315.477]}
						rotation={[-Math.PI / 2, 0, 0]}
					>
						<group position={[535.251, -315.476, -12.688]}>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.BIG_1_BiG_0.geometry}
								material={materials.material_1}
								position={[-2559.812, 792.434, 0]}
							/>
						</group>
					</group>
					<group
						position={[-243.069, 16.149, -311.823]}
						rotation={[-Math.PI / 2, 0, 0]}
					>
						<group position={[243.069, -311.823, 19.313]}>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.Big_2_BiG_0.geometry}
								material={materials.material_1}
								position={[-2705.348, 1252.623, 0]}
							/>
						</group>
					</group>
					<group
						position={[15.298, 45.34, -290.196]}
						rotation={[-Math.PI / 2, 0, 0]}
					>
						<group position={[-15.298, -290.196, -9.878]}>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.Big_3_BiG_0.geometry}
								material={materials.material_1}
								position={[-2895.527, 457.136, 0]}
							/>
						</group>
					</group>
					<group
						position={[221.833, 26.41, -247.651]}
						rotation={[-Math.PI / 2, 0, 0]}
					>
						<group position={[-221.833, -247.65, 9.052]}>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.Big_4_BiG_0.geometry}
								material={materials.material_1}
								position={[-2865.639, 1504.569, 0]}
							/>
						</group>
					</group>
					<group
						position={[-997.306, 53.851, 340.804]}
						rotation={[-Math.PI / 2, 0, 0]}
					>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.p1_p1_0.geometry}
							material={materials.material_4}
							position={[-1156.453, -962.408, 0]}
							rotation={[0, 0, 1.682]}
						/>
					</group>
					<group
						position={[-122.958, 19.497, 319.928]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={0.853}
					>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.p2_p2_0.geometry}
							material={materials.material_5}
							position={[-874.347, -3.556, -33.953]}
						/>
					</group>
					<group
						position={[-221.9, -3.997, 316.302]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={0.702}
					>
						<group position={[274.002, 339.969, 8.52]}>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.Runic_1_Runic_0.geometry}
								material={materials.Runic}
								position={[-2793.921, -102.567, 0]}
								rotation={[0, 0, 1.682]}
							/>
						</group>
					</group>
					<group
						position={[-176.505, -4.319, 313.012]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={0.702}
					>
						<group position={[209.331, 335.283, 8.979]}>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.Runic_2_Runic_0.geometry}
								material={materials.Runic}
								position={[-2580.659, 129.558, 0]}
								rotation={[0, 0, 1.682]}
							/>
						</group>
					</group>
					<group
						position={[-132.541, -2.065, 314.83]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={0.702}
					>
						<group position={[146.699, 337.872, 5.767]}>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.Runic_3_Runic_0.geometry}
								material={materials.Runic}
								position={[-1988.716, -39.087, 0]}
								rotation={[0, 0, 1.682]}
							/>
						</group>
					</group>
					<group
						position={[-79.196, -4.984, 315.643]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={0.702}
					>
						<group position={[70.702, 339.029, 9.926]}>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.Runic_4_Runic_0.geometry}
								material={materials.Runic}
								position={[-1967.054, -524.209, 0]}
								rotation={[0, 0, 1.682]}
							/>
						</group>
					</group>
					<group
						position={[-18.432, -5.915, 316.192]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={0.702}
					>
						<group position={[-15.865, 339.813, 11.252]}>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.Runic_5_Runic_0.geometry}
								material={materials.Runic}
								position={[-2509.948, -697.028, 0]}
								rotation={[0, 0, 1.682]}
							/>
						</group>
					</group>
					<group
						position={[45.599, -4.127, 316.29]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={0.702}
					>
						<group position={[-107.086, 339.951, 8.705]}>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.Runic_6_Runic_0.geometry}
								material={materials.Runic}
								position={[-1694.716, -798.984, 0]}
								rotation={[0, 0, 1.682]}
							/>
						</group>
					</group>
					<group
						position={[104.636, -5.614, 317.053]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={0.702}
					>
						<group position={[-191.192, 341.039, 10.823]}>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.Runic_7_Runic_0.geometry}
								material={materials.Runic}
								position={[-1675.676, -245.03, 0]}
								rotation={[0, 0, 1.682]}
							/>
						</group>
					</group>
				</group>
			</group>
			<group position={[2.897, 0, 3.277]} rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.doska1_low_defolt_0.geometry}
							material={materials["defolt.001"]}
							position={[32, 0, 0]}
						/>
					</group>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.doska2_low_defolt_0.geometry}
							material={materials.defolt}
							position={[32, 0, 0]}
						/>
					</group>
					<group
						position={[-1.465, 0, 0]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={0}
					>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.flag_low_defolt_0.geometry}
							material={materials.defolt}
							position={[-32, 0, 0]}
						/>
					</group>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.grib2_low_defolt_0.geometry}
							material={materials.defolt}
							position={[32, 0, 0]}
						/>
					</group>
					<group
						position={[-1.465, 0, 0]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={0}
					>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.gvozd_low_defolt_0.geometry}
							material={materials.defolt}
							position={[-32, 0, 0]}
						/>
					</group>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.kryshka_low_defolt_0.geometry}
							material={materials.defolt}
							position={[32, 0, 0]}
						/>
					</group>
					<group scale={0.01}>
						<group
							position={[0.002, 0, 0]}
							rotation={[-Math.PI, 0.876, -Math.PI]}
						>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.grass_low001_Material_0.geometry}
								material={materials["Material.001"]}
								position={[-0.002, 0, 0.001]}
							/>
						</group>
						<group position={[0.002, 0, 0]}>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.mail_low003_defolt_0.geometry}
								material={materials.defolt}
								position={[0.002, 0, 0]}
							/>
						</group>
					</group>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.mash2_low_defolt_0.geometry}
							material={materials.defolt}
							position={[32, 0, 0]}
						/>
					</group>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.mash3_low_defolt_0.geometry}
							material={materials.defolt}
							position={[32, 0, 0]}
						/>
					</group>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.mash4_low_defolt_0.geometry}
							material={materials.defolt}
							position={[32, 0, 0]}
						/>
					</group>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.mash5_low_defolt_0.geometry}
							material={materials.defolt}
							position={[32, 0, 0]}
						/>
					</group>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.mash_low_defolt_0.geometry}
							material={materials.defolt}
							position={[32, 0, 0]}
						/>
					</group>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.stolb_low_defolt_0.geometry}
							material={materials.defolt}
							position={[32, 0, 0]}
						/>
					</group>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.zemlya_low_defolt_0.geometry}
							material={materials.defolt}
							position={[32, 0, 0]}
						/>
					</group>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.box_low_defolt_0.geometry}
						material={materials.defolt}
						position={[-1.55, 0, 0]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={0}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.mail_low_defolt_0.geometry}
						material={materials.defolt}
						position={[6.502, 161.842, 94.706]}
						rotation={[-1.57, 0.643, 1.56]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.mail_low001_defolt_0.geometry}
						material={materials.defolt}
						position={[-13.642, 165.02, 82.145]}
						rotation={[-1.292, 1.183, 1.334]}
					/>
				</group>
			</group>
			<group
				position={[-31.837, 0, 90.74]}
				rotation={[-Math.PI / 2, 0, 1.627]}
				scale={0.084}
			>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.herbalistBox_final_BoxMaterial_0.geometry}
						material={materials.BoxMaterial}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial_VialYellow_0.geometry}
						material={materials.VialYellow}
						position={[8.868, 1.941, -4.691]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial001_VialYellow_0.geometry}
						material={materials.VialYellow}
						position={[4.968, 1.941, -4.827]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial002_VialYellow_0.geometry}
						material={materials.VialYellow}
						position={[-1.177, 1.941, 1.423]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial003_VialYellow_0.geometry}
						material={materials.VialYellow}
						position={[9.328, 1.941, 1.326]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial004_VialRed_0.geometry}
						material={materials.VialRed}
						position={[9.245, 1.941, -1.973]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial005_VialYellow_0.geometry}
						material={materials.VialYellow}
						position={[-6.349, 1.941, -4.716]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial006_VialRed_0.geometry}
						material={materials.VialRed}
						position={[8.888, 1.941, 4.618]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial007_VialRed_0.geometry}
						material={materials.VialRed}
						position={[-7.581, 1.941, -1.852]}
						rotation={[-Math.PI / 2, 0, 1.008]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial008_VialRed_0.geometry}
						material={materials.VialRed}
						position={[-4.538, 1.941, 1.641]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial009_VialNeutral_0.geometry}
						material={materials.VialNeutral}
						position={[5.904, 1.941, 4.904]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial010_VialRed_0.geometry}
						material={materials.VialRed}
						position={[3.213, 1.941, -1.669]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial011_VialRed_0.geometry}
						material={materials.VialRed}
						position={[2.718, 1.941, 4.756]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial012_VialRed_0.geometry}
						material={materials.VialRed}
						position={[-0.335, 1.941, -1.402]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial013_VialNeutral_0.geometry}
						material={materials.VialNeutral}
						position={[-1.012, 1.941, 4.646]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial014_VialNeutral_0.geometry}
						material={materials.VialNeutral}
						position={[-4.162, 1.941, -1.407]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial015_VialRed_0.geometry}
						material={materials.VialRed}
						position={[-4.564, 1.941, 4.666]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial016_VialRed_0.geometry}
						material={materials.VialRed}
						position={[0.719, 1.941, -4.608]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial017_VialRed_0.geometry}
						material={materials.VialRed}
						position={[-2.957, 1.941, -3.753]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial018_VialNeutral_0.geometry}
						material={materials.VialNeutral}
						position={[-9.245, 11.999, -10.693]}
						rotation={[-Math.PI / 2, 0, -0.412]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial019_VialYellow_0.geometry}
						material={materials.VialYellow}
						position={[-5.858, 11.997, -10.408]}
						rotation={[-Math.PI / 2, 0, 0.477]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial020_VialRed_0.geometry}
						material={materials.VialRed}
						position={[-2.436, 12.001, -10.864]}
						rotation={[-Math.PI / 2, 0, 0.429]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial021_VialRed_0.geometry}
						material={materials.VialRed}
						position={[1.107, 11.997, -10.417]}
						rotation={[-Math.PI / 2, 0, 0.497]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial022_VialNeutral_0.geometry}
						material={materials.VialNeutral}
						position={[4.692, 12.003, -11.051]}
						rotation={[-Math.PI / 2, 0, -0.239]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial023_VialRed_0.geometry}
						material={materials.VialRed}
						position={[8.53, 12, -10.774]}
						rotation={[-Math.PI / 2, 0, 0.445]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial024_VialYellow_0.geometry}
						material={materials.VialYellow}
						position={[17.068, 0, 14.321]}
						rotation={[-Math.PI / 2, 0, -2.159]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial025_VialNeutral_0.geometry}
						material={materials.VialNeutral}
						position={[19.315, 0, 19.427]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Vial026_VialYellow_0.geometry}
						material={materials.VialYellow}
						position={[9.63, 1.577, 9.689]}
						rotation={[0, 0.448, 0]}
						scale={100}
					/>
				</group>
			</group>
			<group
				position={[-0.329, 2.624, -1.419]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={13.614}
			>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01_leafes_Mat001_0004.geometry}
						material={materials["leafes_Mat.001"]}
						position={[-51.373, -20.175, -2.192]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01_leafes_Mat001_0005.geometry}
						material={materials["leafes_Mat.001"]}
						position={[-51.373, -20.175, -2.192]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01_leafes_Mat001_0006.geometry}
						material={materials["leafes_Mat.001"]}
						position={[0, -23.669, -33.36]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01_leafes_Mat001_0007.geometry}
						material={materials["leafes_Mat.001"]}
						position={[0, -23.669, -33.36]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01001_trunk_Mat001_0006.geometry}
						material={materials["trunk_Mat.001"]}
						position={[-51.373, -20.175, -2.192]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01001_trunk_Mat001_0007.geometry}
						material={materials["trunk_Mat.001"]}
						position={[-51.373, -20.175, -2.192]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01001_trunk_Mat001_0008.geometry}
						material={materials["trunk_Mat.001"]}
						position={[-51.373, -20.175, -2.192]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01001_trunk_Mat001_0009.geometry}
						material={materials["trunk_Mat.001"]}
						position={[0, -23.669, -33.36]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01001_trunk_Mat001_0010.geometry}
						material={materials["trunk_Mat.001"]}
						position={[0, -23.669, -33.36]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01001_trunk_Mat001_0011.geometry}
						material={materials["trunk_Mat.001"]}
						position={[0, -23.669, -33.36]}
					/>
				</group>
			</group>
			<group
				position={[3.076, -0.171, -2.11]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={13.614}
			>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01_leafes_Mat001_0008.geometry}
						material={materials["leafes_Mat.001"]}
						position={[12.114, 0, -6.712]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01_leafes_Mat001_0009.geometry}
						material={materials["leafes_Mat.001"]}
						position={[12.114, 0, -6.712]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01001_trunk_Mat001_0012.geometry}
						material={materials["trunk_Mat.001"]}
						position={[12.114, 0, -6.712]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01001_trunk_Mat001_0013.geometry}
						material={materials["trunk_Mat.001"]}
						position={[12.114, 0, -6.712]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oak_01001_trunk_Mat001_0014.geometry}
						material={materials["trunk_Mat.001"]}
						position={[12.114, 0, -6.712]}
					/>
				</group>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube046.geometry}
				material={materials.Billboard}
				position={[95.83, 0, 38.394]}
				rotation={[0, -1.561, 0]}
				scale={1.5}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane.geometry}
				material={materials["Grass and stones"]}
				position={[-24.924, 0, 52.859]}
				scale={190.287}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube001.geometry}
				material={materials.Billboard}
				position={[66, 0, -14.263]}
				rotation={[0, -1.561, 0]}
				scale={1.5}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube002.geometry}
				material={materials.Billboard}
				position={[66, 0, 95.266]}
				rotation={[0, -1.561, 0]}
				scale={1.5}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube003.geometry}
				material={materials.Billboard}
				position={[81, 0, 70]}
				rotation={[0, -1.561, 0]}
				scale={1.5}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube004.geometry}
				material={materials.Billboard}
				position={[81, 0, 6]}
				rotation={[0, -1.561, 0]}
				scale={1.5}
			/>
		</group>
	);
}

useGLTF.preload("/new-scene.glb");
