/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function PrunedPortfolioAvatar(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF(
		"/PrunedPortfolioAvatar.glb"
	);
	const { actions } = useAnimations(animations, group);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<group name="Armature" position={[0, 0, -1.986]}>
					<skinnedMesh
						name="Body"
						geometry={nodes.Body.geometry}
						material={materials["Knight_MAT2.002"]}
						skeleton={nodes.Body.skeleton}
					/>
					<skinnedMesh
						name="Head_Hands"
						geometry={nodes.Head_Hands.geometry}
						material={materials["Knight_MAT2.002"]}
						skeleton={nodes.Head_Hands.skeleton}
					/>
					<skinnedMesh
						name="Lower_Armor"
						geometry={nodes.Lower_Armor.geometry}
						material={materials["Knight_MAT2.002"]}
						skeleton={nodes.Lower_Armor.skeleton}
					/>
					<primitive object={nodes.mixamorigHips} />
					<primitive object={nodes.Ctrl_Master} />
					<primitive object={nodes.Ctrl_ArmPole_IK_Left} />
					<primitive object={nodes.Ctrl_Hand_IK_Left} />
					<primitive object={nodes.Ctrl_ArmPole_IK_Right} />
					<primitive object={nodes.Ctrl_Hand_IK_Right} />
					<primitive object={nodes.Ctrl_Foot_IK_Left} />
					<primitive object={nodes.Ctrl_LegPole_IK_Left} />
					<primitive object={nodes.Ctrl_Foot_IK_Right} />
					<primitive object={nodes.Ctrl_LegPole_IK_Right} />
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/PrunedPortfolioAvatar.glb");
