/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, Outlines } from "@react-three/drei";

export default function Reactlogo(props) {
	const { nodes, materials } = useGLTF("/reactLogo.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, -Math.PI / 4]} position={[0, 0.5, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<group>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes["React-Logo_Material002_0"].geometry}
							material={materials["Material.003"]}
							position={[0, 7.935, 0]}
							rotation={[-Math.PI / 2, Math.PI / 2, 0]}
							scale={[39.166, 39.166, 52.734]}
						/>
						<Outlines />
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/reactLogo.glb");
