/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Terrain(props) {
	const { nodes, materials } = useGLTF("/terrain.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Mesh_0.geometry}
				material={materials.Material_0}
				scale={0.019}
			/>
		</group>
	);
}

useGLTF.preload("/terrain.glb");
