/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export default function Terrain(props) {
	const { nodes, materials } = useGLTF("/terrain.glb");
	return (
		<>
			{/* Invisible Boundary */}
			<RigidBody type="fixed" colliders="trimesh" includeInvisible scale={7}>
				<mesh visible={false}>
					<sphereGeometry args={[15, 6, 6]} />
					<meshStandardMaterial />
				</mesh>
			</RigidBody>
			<group {...props} dispose={null}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Mesh_0.geometry}
					material={materials.Material_0}
					scale={0.019}
				/>
			</group>
		</>
	);
}

useGLTF.preload("/terrain.glb");
