/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function ThreeLogo(props) {
	const { nodes, materials } = useGLTF("/threeLogo.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				position={[0, 20, 0]}
				rotation={[0, 1, 0]}
				castShadow
				receiveShadow
				geometry={nodes.Object_5.geometry}
				// material={materials.material_0}
			/>
		</group>
	);
}

useGLTF.preload("/threeLogo.glb");
