/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/land.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Land(props) {
	const { nodes, materials } = useGLTF("/land.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.terrain.geometry}
				material={materials.terrain}
				scale={[600, 1, 600]}
			/>
		</group>
	);
}

useGLTF.preload("/land.glb");
