/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/tree.glb
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Tree(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/tree.glb");
	const { actions } = useAnimations(animations, group);

	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<mesh
					position={[-70, 1, 1]}
					name="Tree_lp_11"
					geometry={nodes.Tree_lp_11.geometry}
					material={materials["Wooden surface"]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.01}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/tree.glb");
